cd a_semi_0.02
cd 1
cd semi_smm_experi
run accuracy_noNullClass_semi_smm_unlab.m 
run accuracy_noNullClass_semi_smm_test.m 
cd ..
cd .. 
cd 2
cd semi_smm_experi
run accuracy_noNullClass_semi_smm_unlab.m 
run accuracy_noNullClass_semi_smm_test.m 
cd ..
cd .. 
cd 3
cd semi_smm_experi
run accuracy_noNullClass_semi_smm_unlab.m 
run accuracy_noNullClass_semi_smm_test.m 
cd ..
cd .. 
cd 4
cd semi_smm_experi
run accuracy_noNullClass_semi_smm_unlab.m 
run accuracy_noNullClass_semi_smm_test.m 
cd ..
cd .. 
cd 5
cd semi_smm_experi
run accuracy_noNullClass_semi_smm_unlab.m 
run accuracy_noNullClass_semi_smm_test.m 
cd ..
cd .. 
cd 6
cd semi_smm_experi
run accuracy_noNullClass_semi_smm_unlab.m 
run accuracy_noNullClass_semi_smm_test.m 
cd ..
cd .. 
cd .. 
